FROM node:alpine

# Extend PATH
ENV PATH=$PATH:/node_modules/.bin

# Set working directory
WORKDIR /manuka-client

# Copy project files for build
COPY package.json .
COPY package-lock.json .

# Install dependencies
RUN npm install --silent

# Add application
COPY . .

# Run create-react-app server
CMD ["npm", "start"]