FROM node:alpine

# Extend PATH
ENV PATH=$PATH:/node_modules/.bin

# Set working directory
WORKDIR /manuka-client

# Copy project files for build
ADD . .

# Install dependencies
RUN npm install

# Run create-react-app server
CMD ["npm", "run", "start"]